app:
  objectsLimit: 100

server:
  port: ${SERVER_PORT}
spring:
  application:
    name: migration
  r2dbc:
    password: postgres
    url: r2dbc:postgresql://${SERVER_HOST:localhost}:5432/migration
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always