app:
  objectsLimit: 100
  cacheSize: ${CACHE_SIZE}
  poolSize: ${POOL_SIZE}

server:
  port: ${SERVER_PORT}
spring:
  application:
    name: migration
  datasource:
    password: postgres
    url: jdbc:postgresql://${SERVER_HOST:localhost}:5432/migration
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always